kind = "mobile"
previewPath = "/"
title = "AnyFight: Dream Battles"
version = "1.0.0"
id = "artifacts/anyfight"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25341

[services.development]
run = "pnpm --filter @workspace/anyfight run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/anyfight", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/anyfight", "run", "serve" ]

[services.env]
PORT = "25341"
BASE_PATH = "/"
